name: TEST

on:
  workflow_dispatch:
    inputs:
      mock_services_list:
        type: string
        default: '["8.8.8.8", "8.8.8.8", "8.8.8.8"]'
        required: true
        description: "Json string with list of mock services to check"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: TEST STEP
        run: |
          while IFS="," read -r element; do
          final=$(echo "$element" | sed -e 's/\\r\|\\n//g')
          mock_service_names+=("$final")
          done < <( echo "$results" | jq -r '.[]')  
  
          for i in "${mock_service_names[@]}"; do
          echo $i
          done
