name: TEST

on:
  workflow_dispatch:
    inputs:
      mock_services_list:
        type: string
        default: '["8.8.8.8", "8.8.8.8", "8.8.8.8"]'
        required: true
        description: "Json string with list of mock services to check"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: TEST STEP
        run: |
          echo ${{ fromJSON(inputs.mock_services_list)}}
          echo ${{ inputs.mock_services_list }}
          results = ${{ fromJSON(inputs.mock_services_list )}}
          for str in "${results[@]}"; do
            echo $str
          done
