name: TEST

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      mock_services_list:
        type: string
        default: '["sv1", "sv2", "sv3", "sv4"]'
        required: true
        description: "Json string with list of mock services to check"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: TEST STEP
        with:
          services: ${{ fromJSON(inputs.mock_services_list)}}
        run: |
          for str in ${services[@]}; do
            echo $str
          done
          
